name: matric_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color : "#f7f6f1"
  color_dark : "#272727"
  image : assets/images/matric splash.png
  image_dark: assets/images/matric splash.png

  android_12 :
  icon_background_color : "#f7f6f1"
  icon_background_color_dark: "#272727"
  

flutter:
  uses-material-design: true
  assets :
    - assets/images/
    - assets/images/welcome_image.png
    - assets/subjects/
